---
- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ registry }}"
    username: "{{ username }}"
    password: "{{ password }}"
    reauthorize: yes

- name: Create volume for app
  docker_volume:
    name: todolistdata
    state: present

- name: Deploy Todolistapp
  community.docker.docker_swarm_service:
    name: todolistapp
    image: "{{ image }}"
    force_update: true
    networks:
      - traefik
    mounts:
      - source: /data
        target: /data
        type: bind
    publish:
      - target_port: 8080
        published_port: 8080
        mode: host
    labels:
      traefik.enable: "true"
      traefik.http.routers.todolistapp.rule: "{{ traefik_rule }}"
      traefik.http.routers.todolistapp.entrypoints: "websecure"
      traefik.http.routers.todolistapp.tls.certresolver: "letsencryptresolver"
      traefik.http.services.todolistapp.loadbalancer.server.port: "8080"