---
- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ registry }}"
    username: "{{ username }}"
    password: "{{ password }}"
    reauthorize: yes

- name: Deploy Todolistapp
  community.docker.docker_swarm_service:
    name: todolistapp
    image: "{{ image }}"
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarqube.rule: "Host(`app.topin060.master-sdl.ovh`)"
      traefik.http.routers.sonarqube.entrypoints: "websecure"
      traefik.http.routers.sonarqube.tls.certresolver: "letsencryptresolver"
      traefik.http.services.sonarqube.loadbalancer.server.port: "9000"