---
- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ registry }}"
    username: "{{ username }}"
    password: "{{ password }}"
    reauthorize: yes

- name: Deploy Todolistapp
  community.docker.docker_swarm_service:
    name: todolistapp
    image: "{{ image }}"
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.todolistapp.rule: "{{ traefik_rule }}"
      traefik.http.routers.todolistapp.entrypoints: "websecure"
      traefik.http.routers.todolistapp.tls.certresolver: "letsencryptresolver"
      traefik.http.services.todolistapp.loadbalancer.server.port: "8080"