---
- name: Create Prometheus data volume
  docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - prometheus_data

- name: Copy Prometheus configuration file
  template:
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_config_path }}"

- name: Deploy Prometheus
  community.docker.docker_swarm_service:
    name: prometheus
    image: "prom/prometheus:latest"
    mounts:
      - source: prometheus_data
        target: /prometheus
        type: volume
      - source: "{{ prometheus_config_path }}"
        target: /etc/prometheus/prometheus.yml
        type: bind
    networks:
      - traefik
    ports:
      - published: 9090
        target: 9090
    env:
      - "TZ=UTC"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: "Host(`{{ traefik_host }}`)"
      traefik.http.routers.prometheus.entrypoints: "websecure"
      traefik.http.routers.prometheus.tls.certresolver: "letsencryptresolver"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"
