---
- name: Create Prometheus data volume
  docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - prometheus_data

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}/.docker"
    state: directory
    mode: '0755'

- name: Copy Prometheus configuration file
  template:
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_config_path }}"
  register: config

- name: Deploy Prometheus
  community.docker.docker_swarm_service:
    name: prometheus
    image: "prom/prometheus:latest"
    mounts:
      - source: prometheus_data
        target: /prometheus
        type: volume
      - source: "{{ prometheus_config_path }}"
        target: /etc/prometheus/prometheus.yml
        type: bind
    networks:
      - traefik
    publish:
      - target_port: 9090
        published_port: 9090
        mode: host
    env:
      - "TZ=UTC"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: "Host(`{{ traefik_host }}`)"
      traefik.http.routers.prometheus.entrypoints: "websecure"
      traefik.http.routers.prometheus.tls.certresolver: "letsencryptresolver"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"

- name: Force update Prometheus service
  command: docker service update --force prometheus
  when: config.changed
