---
- name: Setup SSH
  hosts: all
  roles:
    - ssh_setup #This role is designed to run only once for preparing the future infra
  when: state == 'ssh'

- name: Install required tools & packages
  block:
    - name: Docker setup
      hosts: all
      roles:
        - docker_install

    - name: Traefik setup
      hosts: all
      roles:
        - traefik_service

    - name: Monitoring setup
      hosts: monitor
      roles:
        - sonar_service
        - prometheus_observer
  when: state == 'tools'

- name: Deploy TodoList App
  hosts:
    - "{{ lookup('env', 'HOST') }}"
  roles:
    - deploy_app
  when: state == 'app'
