---
- name: Set up Docker's apt repository
  become: true
  block:
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install necessary packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to Apt sources
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker.list

    - name: Update Apt cache
      apt:
        update_cache: yes

- name: Install and set docker env
  become: true
  block:
    - name: Install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add docker group
      group:
        name: docker
        state: present

    - name: Add GHA user to docker group
      user:
        name: GHA
        group: docker
        append: yes

- name: Init a new swarm with default parameters
  community.docker.docker_swarm:
    state: present